_target_: src.models.unetplusplus_module.UNetPlusPlusModule

defaults:
  - net: unetplusplus.yaml
  - _self_

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

loss: "ce"
weight: [1, 50]