# @package _global_

defaults:
  - _self_
  - data: lidc.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: efsp_module.yaml
  - logger: wandb
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /work/hpc/dqm/Lung-Nodule-Segmentation/checkpoints/esfp_full_data.ckpt
